DROP TABLE IF EXISTS produtos;

CREATE TABLE IF NOT EXISTS produtos (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nome VARCHAR(100) NOT NULL,
  valor DECIMAL(11,2) NOT NULL,
  cod_barras VARCHAR(20) NOT NULL,
  dt_exclusao DATE DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;